pipeline {
    agent any
    environment{
        IMAGE_TAG="{GIT_COMMIT.take(2)}"         
    }
    stages{
        stage('Docker login'){
            steps{
                withCredentials([UsernamePassword(CredentialsId:'docker_creds', usernameVariable:'username', passwordVariable:'password')])
            }
            steps{
                sh 'echo ${password} | docker login -u ${username} --password-stdin'
            }
        }
        stage('docker build'){
            steps{
                sh "docker build -t botadmin/opentelemetry/ad:${IMAGE_TAG} ./src/ad/"
            }
        }
        stage('docker push'){
            steps{
                 sh  "docker push botadmin/opentelemetry/ad:${IMAGE_TAG}"
            }
        }         
        }
    }
