pipeline {
    agent any
    environment{
        IMAGE_TAG = "${env.GIT_COMMIT.take(2)}"
    }
    stages{
        stage('docker login'){
            steps{
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'docker_creds',
                        usernameVariable: 'username',
                        passwordVariable: 'password'
                    )]) {
                        sh 'echo "$password" | docker login -u "$username" --password-stdin'
                    }
                }
            }
        }
        stage('docker image build'){
            steps{
                sh "docker build -t botadmin/project2:${IMAGE_TAG} ./src/recommendation"
                echo "success"
            }
        }
        stage('docker image push'){
            steps{
                sh "docker push botadmin/project2:${IMAGE_TAG}"
                echo "success"
            }
        }
    }
}