pipeline {
    agent any
    withCredentials([UsernamePassword(CredentialsId:'docker_creds', usernameVariable:'username', passwordVariable:'password')])
    environment{
        IMAGE_TAG = "${GIT_COMMIT.take(2)}"
    }
    stages{
        stage('docker login'){
            steps{
                sh 'echo ${password}|docker login -u ${username} --password-stdin'
                echo "success"
            }
        }
        stage('docker image build'){
            steps{
                sh "docker build -t botadmin/project2:${IMAGE_TAG} ./src/recommendation"
                echo "success"
            }
        }
        stage('docker image push'){
            steps{
                sh "docker push botadmin/project2:${IMAGE_TAG}"
                echo "success"
            }
        }
    }
}